config/routes.rb
Rails.application.routes.draw do
  resources :mining_types
  resources :mining_types
  get 'welcome/index'
  get '/inicio', to: 'welcome#index' # Setando /inicio para welcome index

  resources :coins#Criando 7rotas para ter o get , post , put e etc

  root to: 'welcome#index' #Pagina padrão welcome/index

end

app/models/coin.rb
class Coin < ActiveRecord::Base
    belongs_to :mining_type
end

app/models/mining_type.rb
class MiningType < ActiveRecord::Base
    has_many :coins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :set_locale
  def set_locale
      if params[:locale]
        cookies[:locale] = params[:locale]
      end
      if cookies[:locale]
        if I18n.locale != cookies[:locale]
          I18n.locale = cookies[:locale]
        end
      end
    end
end

app/controllers/coins_controller.rb
class CoinsController < ApplicationController
  before_action :set_coin, only: [:show, :edit, :update, :destroy]
  before_action :set_mining_type_options, only:[:new,:edit,:update]

  # GET /coins
  # GET /coins.json
  def index
    @coins = Coin.all
  end

  # GET /coins/1
  # GET /coins/1.json
  def show
  end

  # GET /coins/new
  def new
    @coin = Coin.new
  end

  # GET /coins/1/edit
  def edit
  end

  # POST /coins
  # POST /coins.json
  def create
    @coin = Coin.new(coin_params)

    respond_to do |format|
      if @coin.save
        format.html { redirect_to @coin, notice: 'Coin was successfully created.' }
        format.json { render :show, status: :created, location: @coin }
      else
        format.html { render :new }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coins/1
  # PATCH/PUT /coins/1.json
  def update
    respond_to do |format|
      if @coin.update(coin_params)
        format.html { redirect_to @coin, notice: 'Coin was successfully updated.' }
        format.json { render :show, status: :ok, location: @coin }
      else
        format.html { render :edit }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coins/1
  # DELETE /coins/1.json
  def destroy
    @coin.destroy
    respond_to do |format|
      format.html { redirect_to coins_url, notice: 'Coin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coin
      @coin = Coin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def coin_params
      params.require(:coin).permit(:description, :acronym, :url_image,:mining_type_id)
    end
    def set_mining_type_options
      @mining_type_options = MiningType.all.map{|c| [c.description,c.id]}
    end
end

app/controllers/mining_types_controller.rb
class MiningTypesController < ApplicationController
  before_action :set_mining_type, only: [:show, :edit, :update, :destroy]

  # GET /mining_types
  # GET /mining_types.json
  def index
    @mining_types = MiningType.all
  end

  # GET /mining_types/1
  # GET /mining_types/1.json
  def show
  end

  # GET /mining_types/new
  def new
    @mining_type = MiningType.new
  end

  # GET /mining_types/1/edit
  def edit
  end

  # POST /mining_types
  # POST /mining_types.json
  def create
    @mining_type = MiningType.new(mining_type_params)

    respond_to do |format|
      if @mining_type.save
        format.html { redirect_to @mining_type, notice: 'Mining type was successfully created.' }
        format.json { render :show, status: :created, location: @mining_type }
      else
        format.html { render :new }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mining_types/1
  # PATCH/PUT /mining_types/1.json
  def update
    respond_to do |format|
      if @mining_type.update(mining_type_params)
        format.html { redirect_to @mining_type, notice: 'Mining type was successfully updated.' }
        format.json { render :show, status: :ok, location: @mining_type }
      else
        format.html { render :edit }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mining_types/1
  # DELETE /mining_types/1.json
  def destroy
    @mining_type.destroy
    respond_to do |format|
      format.html { redirect_to mining_types_url, notice: 'Mining type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mining_type
      @mining_type = MiningType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mining_type_params
      params.require(:mining_type).permit(:description, :acronym)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    #pode ser usado para enviar funçõe para todas as paginas da view que precisar 


    #Exemplo
    
    # def ambiente
    #    if Rails.env.development?
     #       "Desenvolvimento"
      #  end
    #end
end

app/helpers/coins_helper.rb
module CoinsHelper
end

app/helpers/mining_types_helper.rb
module MiningTypesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/coins/_form.html.erb
<%= form_for(@coin) do |f| %>
  <% if @coin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@coin.errors.count, "error") %> prohibited this coin from being saved:</h2>

      <ul>
      <% @coin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description ,  class:"form-control"%>
  </div>
  <div class="form-group">
    <%= f.label :acronym %><br>
    <%= f.text_field :acronym ,  class:"form-control"%>
  </div>
   <div class="form-group">
    <%=f.label :mining_type %><br>
    <%= f.select("mining_type_id", @mining_type_options,{include_blank:'Selecione uma opção'},  class:"form-control")%>
  </div>
  <div class="form-group">
    <%= f.label :url_images %><br>
    <%= f.text_field :url_image ,  class:"form-control"%>
  </div>
  <div class="form-group">
    <%= f.label "Imagem" %><br>
    <%= image_tag @coin.url_image,witdh:25, height:25 %>
  </div>
  <div class="actions">
    <%= f.submit nil, class:"btn bnt-primary" %>
  </div>
<% end %>

app/views/coins/edit.html.erb
<h1><%=t('links.editing')%></h1>

<%= render 'form' %>

<%= link_to t('links.show'), @coin , class:"btn btn-light"%> |
<%= link_to t('links.back'), coins_path, class:"btn btn-light" %>

app/views/coins/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%=Coin.model_name.human(count: @coins.count)%></h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th><%=Coin.human_attribute_name(:description)%></th>
      <th><%=Coin.human_attribute_name(:acronym)%></th>
      <th><%=Coin.human_attribute_name(:url_image)%></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coins.each do |coin| %>
      <tr>
        <td><%= coin.description %></td>
        <td><%= coin.acronym %></td>
        <td><img src="<%= coin.url_image %>" wifht="25px", height="25px"/></td>
        <td><%= link_to t('links.show'), coin %></td>
        <td><%= link_to t('links.edit'), edit_coin_path(coin) %></td>
        <td><%= link_to t('links.delete'), coin, method: :delete, data: { confirm: t('links.confirm') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('links.new'), new_coin_path %>

app/views/coins/new.html.erb
<h1><%=t('links.new')%></h1>

<%= render 'form' %>

<%= link_to t('links.back'), coins_path , class:"btn btn-light"%>

app/views/coins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%=Coin.human_attribute_name(:description)%>:</strong>
  <%= @coin.description %>
</p>

<p>
  <strong><%=Coin.human_attribute_name(:acronym)%>:</strong>
  <%= @coin.acronym %>
</p>

<p>
  <strong><%=Coin.human_attribute_name(:url_image)%></strong>
  <%= @coin.url_image %>
</p>
<p>
  <strong>Imagem</strong>
  <img src="<%= @coin.url_image %>" wifht="25px", height="25px"/>
</p>

<%= link_to t('links.show'), edit_coin_path(@coin) %> |
<%= link_to t('links.back'), coins_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Teste</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    params[:controller], media: 'all', 'data-turbolinks-track' => true %>
  

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag params[:controller], 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container-fluid">
    <ul class="nav justify-content-end">
      <li class="nav-item">
         <%= link_to t('pt'), '/?locale=pt-BR',class: "nav-link active" %>
      </li>
      <li class="nav-item">
        <%= link_to t('eng'), '/?locale=en',class: "nav-link active"%>
      </li>
  </ul>
    <%= yield %> <!--É todo aqruivo html que é chamado-->
  </div>
</body>
</html>

app/views/mining_types/_form.html.erb
<%= form_for(@mining_type) do |f| %>
  <% if @mining_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mining_type.errors.count, "error") %> prohibited this mining_type from being saved:</h2>

      <ul>
      <% @mining_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description,  class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :acronym %><br>
    <%= f.text_field :acronym ,  class:"form-control"%>
  </div>
  <div class="actions">
    <%= f.submit nil, class:"btn bnt-primary"%>
  </div>
<% end %>

app/views/mining_types/edit.html.erb
<h1><%=t('links.editing')%></h1>

<%= render 'form' %>

<%= link_to t('links.show'), @mining_type , class:"btn btn-light"%> 
<%= link_to t('links.back'), mining_types_path , class:"btn btn-light"%>

app/views/mining_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%=MiningType.model_name.human(count: @mining_types.count)%></h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th><%= @mining_types.human_attribute_name(:description)%></th>
      <th><%= @mining_types.human_attribute_name(:acronym)%></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mining_types.each do |mining_type| %>
      <tr>
        <td><%= mining_type.description %></td>
        <td><%= mining_type.acronym %></td>
        <td><%= link_to t('links.show'), mining_type %></td>
        <td><%= link_to t('links.edit'), edit_mining_type_path(mining_type) %></td>
        <td><%= link_to t('links.delete'), mining_type, method: :delete, data: { confirm: t('links.confirm') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('links.new'), new_mining_type_path %>

app/views/mining_types/new.html.erb
<h1><%=t('links.newm')%></h1>

<%= render 'form' %>

<%= link_to t('links.back'), mining_types_path , class:"btn btn-light"%>

app/views/mining_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%=MiningType.human_attribute_name(:description)%>:</strong>
  <%= @mining_type.description %>
</p>

<p>
  <strong><%=MiningType.human_attribute_name(:acronym)%>:</strong>
  <%= @mining_type.acronym %>
</p>

<%= link_to t('links.edit'), edit_mining_type_path(@mining_type) %> |
<%= link_to t('links.back'), mining_types_path %>

app/views/welcome/_menu.html.erb
<%=link_to t('create_coin'), "/coins",class:"btn btn-primary btn-lg",role:"button"%>
<%=link_to t('create_mt'), "/mining_types",class:"btn btn-primary btn-lg",role:"button"%>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1 class="display-4"><%=t('welcome')%></h1>
  <p class="lead"><%=t('desc')%></p>
  <hr class="my-4">
  <p><%=t('choose')%></p>
  <%= render "menu"%>
</div>




<!-- <p>Você está no ambiente de <%#= ambiente%></p>--> 
<!--Chamando a funcação do helper-->